[package]
name = "typed-emitter"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
uuid = { version = "1.11.0", features = ["v4"] }


[dependencies.tokio]
version = "1.33.0"
features = ["rt", "macros", "rt-multi-thread"]
optional = true
[dependencies.async-std]
version = "1.12.0"
optional = true
features = ["alloc", "attributes"]


[features]
use-async-std = ["async-std"]
default = ["tokio"]
