[package]
name = "typed-emitter"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
uuid = { version = "1.11.0", features = ["v4"] }


[dev-dependencies]
async-std = { version = "1.12.0", features = ["alloc", "attributes"] }
tokio = { version = "1.41.1", default-features = false, features = [
    "rt",
    "macros",
    "rt-multi-thread",
] }
smol-macros = "0.1.1"

macro_rules_attribute = "0.2.0"
